name: exam_bloc_cart
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3  
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  bloc_test: ^9.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true